// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 785LmUYPoUm6pacfNyEDZ9
// Component: -fKdY0THT-
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { antTable } from "@ant/DatePicker"; // plasmic-import: -uZM-JzB4m/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_ant_design_views_wih_codegen.module.css"; // plasmic-import: 785LmUYPoUm6pacfNyEDZ9/projectcss
import sty from "./PlasmicUserViewPage.module.css"; // plasmic-import: -fKdY0THT-/css

export type PlasmicUserViewPage__VariantMembers = {};

export type PlasmicUserViewPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicUserViewPage__VariantsArgs;
export const PlasmicUserViewPage__VariantProps = new Array<VariantPropType>();

export type PlasmicUserViewPage__ArgsType = {};
type ArgPropType = keyof PlasmicUserViewPage__ArgsType;
export const PlasmicUserViewPage__ArgProps = new Array<ArgPropType>();

export type PlasmicUserViewPage__OverridesType = {
  root?: p.Flex<"div">;
  antTable?: p.Flex<typeof antTable>;
};

export interface DefaultUserViewPageProps {}

function PlasmicUserViewPage__RenderFunc(props: {
  variants: PlasmicUserViewPage__VariantsArgs;
  args: PlasmicUserViewPage__ArgsType;
  overrides: PlasmicUserViewPage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <antTable
            data-plasmic-name={"antTable"}
            data-plasmic-override={overrides.antTable}
            className={classNames("__wab_instance", sty.antTable)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "antTable"],
  antTable: ["antTable"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  antTable: typeof antTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUserViewPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUserViewPage__VariantsArgs;
    args?: PlasmicUserViewPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUserViewPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicUserViewPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicUserViewPage__ArgProps,
          internalVariantPropNames: PlasmicUserViewPage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicUserViewPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUserViewPage";
  } else {
    func.displayName = `PlasmicUserViewPage.${nodeName}`;
  }
  return func;
}

export const PlasmicUserViewPage = Object.assign(
  // Top-level PlasmicUserViewPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    antTable: makeNodeComponent("antTable"),

    // Metadata about props expected for PlasmicUserViewPage
    internalVariantProps: PlasmicUserViewPage__VariantProps,
    internalArgProps: PlasmicUserViewPage__ArgProps
  }
);

export default PlasmicUserViewPage;
/* prettier-ignore-end */
